services:
  interview-service:
    build:
      context: .
      dockerfile: Dockerfile.java21
    image: localhost/interview-service:java21
    container_name: interview-service
    ports:
      - "8080:8080"
    restart: unless-stopped
